### ISSUE TITLE
Windows 7 - plugin_host.exe crash

### ISSUE THREAD

**Issue by bdeonovic** [quinnj/Sublime-IJulia#68]
I get the following error:

```
the procedure entry point _ZSt24__throw_out_of_range_fmtPKcz could not be located in the dynamic link library libstdc++-6.dll
```

I downloaded the windows julia 64 bit binary, but I did not see anything like julia-readline.exe (only julia.exe) so I pointed my IJulia preferences to that in Sublime. Here is the output in the console on startup:

```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Benjamin Deonovic/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Benjamin Deonovic/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Benjamin Deonovic/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0774561
startup time: 0.106456
first paint time: 0.107456
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin IJulia.__init__
reloading plugin IJulia.IJulia
reloading plugin IJulia.JuliaSyntax
reloading plugin IJulia.Kernel
plugins loaded
C:\Users\Benjamin Deonovic\AppData\Roaming\Sublime Text 3\Packages\IJulia/windeps/
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\Benjamin Deonovic\AppData\Roaming\Sublime Text 3\Packages\IJulia\Kernel.py", line 22, in plugin_loaded
    zmq = cdll.LoadLibrary(zmq_lib)
  File "./ctypes/__init__.py", line 431, in LoadLibrary
  File "./ctypes/__init__.py", line 353, in __init__
OSError: [WinError 127] The specified procedure could not be found
Package Control: Skipping automatic upgrade, last run at 2015-04-22 09:23:33, next run at 2015-04-22 10:23:33 or after
```

**Comment by michal-gh** [comment]
I had the same problem. It is caused by incompatibility between libraries in ...\AppData\Roaming\Sublime Text 3\Packages\IJulia\windeps and in ...\Julia-0.3.8\bin . I solved it by copying both libraries from Julia install dir (libstc++-6.dll, libgcc_s_seh_1.dll into windeps dir.
I really think that including binary libaries in the package is a mistake. It's much better to use up-to-date libaries from Julia install. It's a small fix in the code, I'll create a pull request in the next few days.

**Comment by bdeonovic** [comment]
Thanks @michal-gh that fixed that error! Now  I am getting the `***kernel Died***` error, but that seems to be more common.

**Comment by michal-gh** [comment]
I also had this problem, it was related to paths in sublime-settings file. I added julia to PATH and set the windows section to:

"windows": {
    "zmq_shared_library": "C:/Users/Michal/.julia/v0.3/WinRPM/deps/usr/x86_64-w64-mingw32/sys-root/mingw/bin/libzmq.dll",
    "commands": [
        {
            "command_name": "default",
            "julia": "julia.exe",
            "julia_args": "",
            "ijulia_kernel": "C:\Users\Michal\.julia\v0.3\IJulia\src\kernel.jl"
        }
    ]
}

I think that you can put Windows backlash-escaped path in julia: "C:\julia\...\bin\julia.exe" and probably change backslashes to slashes in "julia_kernel".
