### ISSUE TITLE
KeyError: 'data' after starting up Kernel , IJulia console doesn't finish starting up

### ISSUE THREAD

**Issue by maresk** [quinnj/Sublime-IJulia#73]
Hi I have been trying to figure out what happened to my working installation of Sublime-IJulia and am coming up short.

Here is the console message which logs a KeyError in Kernel.py. The Kernel starts up but the IJulia welcome message doesn't show up and there is no prompt, instead ticker message reads "IJulia Kernel is working" with these messages in the console. I had a working installation and am not sure what might be the issue here.

Starting IJulia backend...
Command Executed: /Applications/Julia-0.3.8.app/Contents/Resources/julia/bin/julia  /Users/druid/.julia/v0.3/IJulia/src/kernel.jl "/Users/druid/Library/Application Support/Sublime Text 3/Packages/User/profile-1.json"
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/druid/Library/Application Support/Sublime Text 3/Packages/IJulia/Kernel.py", line 412, in run
    r = self.handlers.get(m, self.pyin_h)()
  File "/Users/druid/Library/Application Support/Sublime Text 3/Packages/IJulia/Kernel.py", line 378, in stdout_h
    data = self.get_stdout()
  File "/Users/druid/Library/Application Support/Sublime Text 3/Packages/IJulia/Kernel.py", line 328, in get_stdout
    data = m.content['data']
KeyError: 'data'

If helpful, here is the Julia version info

Julia Version 0.3.8
Commit 79599ad (2015-04-30 23:40 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     T8300  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

I tried a fresh install of sublime text (Build 3083) and reinstalling Package Control and reinstalling the IJulia package and the correct user settings for ZMQ and julia kernel path etc but still get the same KeyError message and can see a successful Julia Kernel in my process list, so I am stumped.  I do remember updating Julia using Pkg.Update() but I don't think that matters here. Thanks.

**Comment by maresk** [comment]
I can confirm the issue is with IJulia 1.0.0, It works after reverting to IJulia 0.2.4 .

**Comment by clee115** [comment]
Hi, I've tried a fresh install of Julia and Sublime (build 3083) and followed the same instructions as above.  Had the exact same error.  I also tried to revert to Julia v. 0.2.4 (& also tried 0.2.5), using the command in Julia: 

> Pkg.pin("IJulia",v"0.2.4") 

And I still get the same error.  Is there any new updates on this?  Not sure if this if this is a compatibility issue with the latest stable versions of Julia and Sublime.  

## Thank you!

Here is my Julia version& Sys info

Julia Version 0.4.0 (2015-10-08 06:20 UTC)
Platform Info:
System: Darwin (x86_64-apple-darwin13.4.0)
OSX Yosemite Version 10.10.5
MacBook Pro (Retina, Late 2013)
Processor 2.8 GHz Intel Core i7 w 16 GB of Memory
Python: (2.7.0) Tried both the Standard version that came with OS X and also tried with Anaconda, both didn't work.

**Comment by clee115** [comment]
I finally got it working on Julia 0.3.0.  Version 0.4.0 works as well.  What's weird is that when I start Sublime, the very first console that I open will not display anything, and only when I open the console (with cmd+shift+p) the second time will the Julia logo actually shows up.  This works with subsequent consoles that I open as well.  Not sure why this is, but attached is my screen shot and specific sublime-console errors:

![image](https://cloud.githubusercontent.com/assets/558044/10523550/f2ee709c-7348-11e5-8757-b5a49b4943ec.png)

The screens in order from the left to the right:  1) test.jl, 2) first console: blank & gave the "KeyError: 'data'", 3) second console: it works, 4) third console: it also works.  

I've replicated this behavior on two machines:

Machine 1 (MacPro Late 2013 with OS X Yosemite 10.10.5):
Julia 0.4.0
ZMQ: 0.3.0
IJulia: 0.2.5 pinned.
Python: standard OSX. v. 2.7.10 with GCC 4.2.1 Apple LLVM

Machine 2 (MacBook Pro 2013 with OS X Yosemite 10.10.5):
Julia 0.3.9
ZMQ: 0.2.0
IJulia: 0.2.5 pinned.
Python: Python v 2.7.10 | Anaconda 2.3.0 (x86_64)

Hopefully this is helpful for anyone who is out there struggling with the same problems.  Would love to hear if there is a permanent fix to this.

**Comment by maresk** [comment]
I can try replicating this on my machine if you could let me know how you got it to work ? If I understand it correctly, just unpinning IJulia and opening the IJulia console two times led to this oddity?
