### ISSUE TITLE
Error starting IJulia plugins on v0.4 and v0.5

### ISSUE THREAD

**Issue by rieser** [quinnj/Sublime-IJulia#79]
I get the following errors when starting IJulia on v0.4 and v0.5:

for v0.4: 

Starting IJulia backend...
Command Executed: julia  /home/user/.julia/v0.4/IJulia/src/kernel.jl "/home/user/.config/sublime-text-3/Packages/User/profile-1.json"
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 412, in run
    r = self.handlers.get(m, self.pyin_h)()
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 378, in stdout_h
    data = self.get_stdout()
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 328, in get_stdout
    data = m.content['data']
KeyError: 'data'

for v0.5, the error is similar:
Starting IJulia backend...
Command Executed: julia  /home/user/.julia/v0.5/IJulia/src/kernel.jl "/home/user/.config/sublime-text-3/Packages/User/profile-1.json"
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 412, in run
    r = self.handlers.get(m, self.pyin_h)()
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 378, in stdout_h
    data = self.get_stdout()
  File "/home/user/.config/sublime-text-3/Packages/IJulia/Kernel.py", line 328, in get_stdout
    data = m.content['data']
KeyError: 'data'

In both cases, a new tab opens in Sublime 3, but the Julia banner never appears.

**Comment by rieser** [comment]
That is, julia versions 0.4 and 0.5

**Comment by carlosfamilia** [comment]
Any news on this?

**Comment by rieser** [comment]
Personally, I just changed to using a different editor and running julia
through the terminal, which, while not ideal, works fine.
